/**:
  ros__parameters:
    plugin_allowlist:
      - sys_status
      - sys_time
      - imu
      - local_position
      - global_position
      - odometry
      - setpoint_position
      - setpoint_velocity
      - distance_sensor
      - param
      - command
      - rc_io
      - manual_control
      - waypoint
