# Common configuration for APM2 autopilot
#
/**:
  ros__parameters:
    startup_px4_usb_quirk: false
    plugin_allowlist:
      - sys
      - time
      - imu
      - local_position
      - global_position
      - odometry
      - setpoint_position
      - setpoint_velocity
      - distance_sensor
      - param
      - cmd
      - rc

# --- system plugins ---

/**/sys:
  ros__parameters:
    min_voltage: [10.0]
    disable_diag: false
    heartbeat_rate: 1.0
    heartbeat_mav_type: "ONBOARD_CONTROLLER"
    conn_timeout: 10.0

/**/time:
  ros__parameters:
    time_ref_source: "fcu"
    timesync_mode: MAVLINK
    timesync_avg_alpha: 0.6
    timesync_rate: 10.0
    system_time_rate: 1.0

# --- mavros plugins ---

/**/cmd:
  ros__parameters:
    use_comp_id_system_control: false

/**/global_position:
  ros__parameters:
    frame_id: "map"
    child_frame_id: "base_link"
    rot_covariance: 99999.0
    gps_uere: 1.0
    use_relative_alt: true
    tf:
      send: false
      frame_id: "map"
      global_frame_id: "earth"
      child_frame_id: "base_link"

/**/imu:
  ros__parameters:
    frame_id: "base_link"
    linear_acceleration_stdev: 0.0003
    angular_velocity_stdev: 0.0003490659
    orientation_stdev: 1.0
    magnetic_stdev: 0.0

/**/local_position:
  ros__parameters:
    frame_id: "map"
    tf:
      send: false
      frame_id: "map"
      child_frame_id: "base_link"
      send_fcu: false

/**/setpoint_position:
  ros__parameters:
    tf:
      listen: false
      frame_id: "map"
      child_frame_id: "target_position"
      rate_limit: 50.0
    mav_frame: LOCAL_NED

/**/guided_target:
  ros__parameters:
    tf:
      listen: false
      frame_id: "map"
      child_frame_id: "target_position"
      rate_limit: 50.0

/**/setpoint_velocity:
  ros__parameters:
    mav_frame: LOCAL_NED

/**/distance_sensor:
  ros__parameters:
    config: |
      rangefinder_pub:
        id: 0
        frame_id: "lidar"
        field_of_view: 0.0
        send_tf: false
        sensor_position: {x: 0.0, y: 0.0, z: -0.1}
      rangefinder_sub:
        subscriber: true
        id: 1
        orientation: PITCH_270

# --- Odometry Plugin Configuration ---
/**/odom:
  ros__parameters:
    fcu:
      odom_parent_id_des: "odom"
      odom_child_id_des: "base_link"

/**/odometry:
  ros__parameters:
    fcu:
      odom_parent_id_des: "odom"
      odom_child_id_des: "base_link"
